#logging.level.com.ml=debug

logging:
  level:
    com.ml: info
#    org.apache.sshd.server.subsystem.sftp: trace

sftp:
  home: /Users/maling/test/ftp
  host-key: /Users/maling/test/ftp/db.ser
  authorization:
    mode: dynamic
#    mode: static
#    users:
#      - username: maling
#        password: 111111
#      - username: lisi
#        password: 111111
debug: false
